### ISSUE TITLE
页面显示为空

### ISSUE THREAD

**Issue by guxuehua** [wyk304443164/hexi#1]
![image](https://user-images.githubusercontent.com/18044466/33159481-39458940-d04e-11e7-8abf-bc68cf259004.png)
console中能够显示内容，但是页面显示为空，麻烦问一下这是什么原因

**Comment by wyk304443164** [comment]
我没有看到，不好意思，他的源码我是稍微改了一下，请问你是直接用的我这边的组件嘛，稍等我写一个demo单独出来

**Comment by wyk304443164** [comment]
请问你是不是看着这一篇修改的：http://blog.csdn.net/wyk304443164/article/details/77977577

**Comment by guxuehua** [comment]
是这这一篇，页面显示为空已经解决了，要求渲染的页面必须也是在一级目录下才能
