### ISSUE TITLE
Setting data field "$htmlParser$myHtmlParserKiner1" to undefined is invalid.

### ISSUE THREAD

**Issue by moedong** [wyk304443164/hexi#2]
参考作者的例子，发现有报错: Setting data field "$htmlParser$myHtmlParserKiner1" to undefined is invalid.

但页面上可以显示数据

**Comment by moedong** [comment]
请问是什么原因呢 @wyk304443164

**Comment by wyk304443164** [comment]
请问，你有跟着我博客上面一步一步来改吗？还是直接复制的上面的那个项目，如果你是复制的项目，你可以看看把整个项目拉下来，看看有没有报错，如果还是有的话，你试着看看升级 wepy 和 小程序的基础库

**Comment by moedong** [comment]
目前的wepy 包是1.7的，把该项目拉下运行的时候，会报错

小程序控制台

VM54:1 thirdScriptError 
 sdk uncaught third Error 
 Cannot set property 'Promise' of undefined 
 TypeError: Cannot set property 'Promise' of undefined
    at http://127.0.0.1:65466/appservice/npm/wepy-async-function/index.js:15:11
    at require (http://127.0.0.1:65466/appservice/__dev__/WAService.js:18:16253)
    at http://127.0.0.1:65466/appservice/__dev__/WAService.js:18:16002
    at http://127.0.0.1:65466/appservice/app.js:23:1
    at require (http://127.0.0.1:65466/appservice/__dev__/WAService.js:18:16253)
    at http://127.0.0.1:65466/appservice/appservice:4045:9
console.error @ VM54:1
(anonymous) @ WAService.js:4
(anonymous) @ WAService.js:4
a @ appservice:4009
window.onerror @ VM54:1
VM54:1 thirdScriptError 
 sdk uncaught third Error 
 Cannot read property '$pages' of undefined 
 TypeError: Cannot read property '$pages' of undefined
    at Object.$createPage (http://127.0.0.1:65466/appservice/npm/wepy/lib/base.js:144:27)
    at http://127.0.0.1:65466/appservice/pages/recommend.js:116:51
    at require (http://127.0.0.1:65466/appservice/__dev__/WAService.js:18:16253)
    at http://127.0.0.1:65466/appservice/appservice:4049:9
console.error @ VM54:1
(anonymous) @ WAService.js:4
(anonymous) @ WAService.js:4
a @ appservice:4009
window.onerror @ VM54:1
appservice:4052 Thu Mar 08 2018 16:15:06 GMT+0800 (中国标准时间) page 编译错误
VM54:1 pages/recommend.js 出现脚本错误或者未正确调用 Page()
console.error @ VM54:1
(anonymous) @ appservice:4053
VM54:1 thirdScriptError 
 sdk uncaught third Error 
 Cannot read property '$pages' of undefined 
 TypeError: Cannot read property '$pages' of undefined
    at Object.$createPage (http://127.0.0.1:65466/appservice/npm/wepy/lib/base.js:144:27)
    at http://127.0.0.1:65466/appservice/pages/home.js:232:51
    at require (http://127.0.0.1:65466/appservice/__dev__/WAService.js:18:16253)
    at http://127.0.0.1:65466/appservice/appservice:4060:9
console.error @ VM54:1
(anonymous) @ WAService.js:4
(anonymous) @ WAService.js:4
a @ appservice:4009
window.onerror @ VM54:1
appservice:4063 Thu Mar 08 2018 16:15:06 GMT+0800 (中国标准时间) page 编译错误
VM54:1 pages/home.js 出现脚本错误或者未正确调用 Page()
console.error @ VM54:1
(anonymous) @ appservice:4064
VM54:1 thirdScriptError 
 sdk uncaught third Error 
 Cannot read property '$pages' of undefined 
 TypeError: Cannot read property '$pages' of undefined
    at Object.$createPage (http://127.0.0.1:65466/appservice/npm/wepy/lib/base.js:144:27)
    at http://127.0.0.1:65466/appservice/pages/index.js:233:51
    at require (http://127.0.0.1:65466/appservice/__dev__/WAService.js:18:16253)
    at http://127.0.0.1:65466/appservice/appservice:4071:9
console.error @ VM54:1
(anonymous) @ WAService.js:4
(anonymous) @ WAService.js:4
a @ appservice:4009
window.onerror @ VM54:1
appservice:4074 Thu Mar 08 2018 16:15:06 GMT+0800 (中国标准时间) page 编译错误
VM54:1 pages/index.js 出现脚本错误或者未正确调用 Page()
console.error @ VM54:1
(anonymous) @ appservice:4075
VM54:1 thirdScriptError 
 sdk uncaught third Error 
 regeneratorRuntime is not defined 
 ReferenceError: regeneratorRuntime is not defined
    at http://127.0.0.1:65466/appservice/components/htmlParser.js:118:51
    at http://127.0.0.1:65466/appservice/components/htmlParser.js:138:6
    at http://127.0.0.1:65466/appservice/components/htmlParser.js:172:2
    at require (http://127.0.0.1:65466/appservice/__dev__/WAService.js:18:16253)
    at http://127.0.0.1:65466/appservice/__dev__/WAService.js:18:16002
    at http://127.0.0.1:65466/appservice/pages/photodetail.js:23:19
    at require (http://127.0.0.1:65466/appservice/__dev__/WAService.js:18:16253)
    at http://127.0.0.1:65466/appservice/appservice:4082:9
console.error @ VM54:1
(anonymous) @ WAService.js:4
(anonymous) @ WAService.js:4
a @ appservice:4009
window.onerror @ VM54:1
appservice:4085 Thu Mar 08 2018 16:15:06 GMT+0800 (中国标准时间) page 编译错误
VM54:1 pages/photodetail.js 出现脚本错误或者未正确调用 Page()
console.error @ VM54:1
(anonymous) @ appservice:4086
VM54:1 thirdScriptError 
 sdk uncaught third Error 
 Cannot read property '$pages' of undefined 
 TypeError: Cannot read property '$pages' of undefined
    at Object.$createPage (http://127.0.0.1:65466/appservice/npm/wepy/lib/base.js:144:27)
    at http://127.0.0.1:65466/appservice/pages/me.js:109:51
    at require (http://127.0.0.1:65466/appservice/__dev__/WAService.js:18:16253)
    at http://127.0.0.1:65466/appservice/appservice:4093:9
console.error @ VM54:1
(anonymous) @ WAService.js:4
(anonymous) @ WAService.js:4
a @ appservice:4009
window.onerror @ VM54:1
appservice:4096 Thu Mar 08 2018 16:15:06 GMT+0800 (中国标准时间) page 编译错误
VM54:1 pages/me.js 出现脚本错误或者未正确调用 Page()
console.error @ VM54:1
(anonymous) @ appservice:4097
VM54:1 thirdScriptError 
 sdk uncaught third Error 
 Cannot read property '$pages' of undefined 
 TypeError: Cannot read property '$pages' of undefined
    at Object.$createPage (http://127.0.0.1:65466/appservice/npm/wepy/lib/base.js:144:27)
    at http://127.0.0.1:65466/appservice/pages/activity.js:74:51
    at require (http://127.0.0.1:65466/appservice/__dev__/WAService.js:18:16253)
    at http://127.0.0.1:65466/appservice/appservice:4104:9
console.error @ VM54:1
(anonymous) @ WAService.js:4
(anonymous) @ WAService.js:4
a @ appservice:4009
window.onerror @ VM54:1
appservice:4107 Thu Mar 08 2018 16:15:06 GMT+0800 (中国标准时间) page 编译错误
VM54:1 pages/activity.js 出现脚本错误或者未正确调用 Page()
console.error @ VM54:1
(anonymous) @ appservice:4108
WAService.js:17 Thu Mar 08 2018 16:15:18 GMT+0800 (中国标准时间) Page route 错误
VM54:1 Page[pages/recommend] not found. May be caused by: 1. Forgot to add page route in app.json. 2. Invoking Page() in async task.

**Comment by wyk304443164** [comment]
请关闭 ES6转换ES5的那几项，这个在wepy里面有写[这边](https://github.com/Tencent/wepy#%E5%BC%80%E5%8F%91%E8%80%85%E5%B7%A5%E5%85%B7%E4%BD%BF%E7%94%A8)

**Comment by moedong** [comment]
ok了，感谢，我认真对照下
